import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on 9. März 2006, 00:33
 */

/**
 *
 * @author peter
 */
public class RootSuite extends TestCase
{
    
    public RootSuite(String testName)
    {
        super(testName);
    }

    protected void setUp() throws Exception
    {
    }

    protected void tearDown() throws Exception
    {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite()
    {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(de.genvlin.core.data.DataSuite.suite());
        return suite;
    }
    
}
