/*
 * DataSuite.java
 * JUnit based test
 *
 * Created on 9. März 2006, 00:33
 */

package de.genvlin.core.data;

import junit.framework.*;

/**
 *
 * @author peter
 */
public class DataSuite extends TestCase {
    
    public DataSuite(String testName) {
        super(testName);
    }
    
    protected void setUp() throws Exception {
    }
    
    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("DataSuite");
        suite.addTest(de.genvlin.core.data.DataVectorTest.suite());
        suite.addTest(de.genvlin.core.data.DoubleVectorTest.suite());
        suite.addTest(de.genvlin.core.data.IDTest.suite());
        suite.addTest(de.genvlin.core.data.IDDataTest.suite());
        suite.addTest(de.genvlin.core.data.IntIDTest.suite());
        suite.addTest(de.genvlin.core.data.MainPoolTest.suite());
        suite.addTest(de.genvlin.core.data.PoolInterfaceTest.suite());
        suite.addTest(de.genvlin.core.data.StringIDTest.suite());
        suite.addTest(de.genvlin.core.data.StringNumberTest.suite());
        suite.addTest(de.genvlin.core.data.VectorPoolTest.suite());
        suite.addTest(de.genvlin.core.data.XYVectorTest.suite());
        suite.addTest(de.genvlin.core.data.XYPoolTest.suite());
        return suite;
    }
    
}
